//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public string Type { get; set; }
        public string AssetId { get; set; }
        public string Author { get; set; }
        public int Id { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
