//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SqlServer
{
    public partial class DevOnlyEntities : DbContext, IDevOnlyEntities
    {
    
        public IDbSet<Asset> Assets
        {
            get { return _assets ?? (_assets = Set<Asset>()); }
        }
        private DbSet<Asset> _assets;

        public IDbSet<Loan> Loans
        {
            get { return _loans ?? (_loans = Set<Loan>()); }
        }
        private DbSet<Loan> _loans;
        
        public IDbSet<Loaned> Loaneds
        {
            get { return _loaneds ?? (_loaneds = Set<Loaned>()); }
        }
        private DbSet<Loaned> _loaneds;
       
        public IDbSet<Member> Members
        {

            get { return _members ?? (_members = Set<Member>()); }
        }
        private DbSet<Member> _members;
    }
}
