//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public string LoanId { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<System.Guid> LoanedId { get; set; }
        public string ReturnIds { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Notes { get; set; }
        public string LinkedLoanId { get; set; }
        public System.Guid MemberId { get; set; }
    
        public virtual Loaned Loaned { get; set; }
        public virtual Member Member { get; set; }
    }
}
